#!/bin/bash

# Get a list of the available defaults (preferences) and export them to plist
# binary files.

now=$(date +%Y-%m-%d-%H-%M-%S)
outdir=defaults-export-$now
preferences=$(defaults domains | tr ',' "$IFS")

mkdir $outdir
for pref in $preferences; do
    echo "$pref"
    defaults export "$pref" "./defaults-export/$pref.plist"
done

# The plists can be imported, although this doesn't always seem to work out.
# defaults import com.name.Thing file.plist
