#!/bin/bash

# Import preferences using `defaults import`. See defaults-export` script.
# This won't work well as Apple change things all the time. But it'll get some
# of the manual labor done.

# It is probably a good idea to delete almost all of the exported plists other
# than select com.apple data.

# https://apple.stackexchange.com/questions/259820/macos-sierra-breaks-a-lot-of-terminal-defaults-write-commands-tap-to-click-fo
# https://eclecticlight.co/2017/11/09/customising-it-all-global-defaults-in-macos-sierra-and-high-sierra/

dir=$1
for file in "$dir"*; do
    name=${file//"$dir"/}
    name=${name//\.plist/}
    defaults import "$name" "$file"
done
