#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# install command line tools
xcode-select --install

# Prompt to install the full xcode
read -p "Install Xcode from the App Store™] and press any key to continue"
sudo xcodebuild -license accept


# set up git cred caching
# git config --global credential.helper osxkeychain

# define app arrays

brew_taps=(
  'PX4/homebrew-px4'
  'bradp/vv'
  'clintmod/formulas'
  'crisidev/homebrew-chunkwm'
  'koekeishiya/formulae'
  'neovim/neovim'
  'osx-cross/avr'
  'rockyluke/devops'
  'rogual/neovim-dot-app'
  'thoughtbot/formulae'
  'universal-ctags/universal-ctags'
)

user_brews=(
  ack
  apple-gcc42
  avr-gcc
  avrdude
  bash
  vv
  cheat
  chunkwm
  cmake
  cmatrix
  cmus
  composer
  coreutils
  cowsay
  dfu-programmer
  dnsmasq
  exiftool
  feh
  ffmpeg
  figlet
  findutils
  fortune
  fswatch
  fzf
  gcc-arm-none-eabi
  gifsicle
  git
  gitlint
  gitsh
  go
  grep
  gtypist
  gpg
  hadolint
  htop
  httrack
  hub
  imagemagick
  khd
  mackup
  macprefs
  mercurial
  mplayer
  mysql
  ncurses
  neofetch
  neovim
  neovim-dot-app
  ngrep
  nmap
  node
  pianobar
  postgresql
  python
  python3
  ranger
  rbenv
  reattach-to-user-namespace
  rename
  ripgrep
  rsync
  ruby-build
  selecta
  shellcheck
  sloccount
  speedtest_cli
  spidermonkey
  ssh-copy-id
  tasksh
  teensy_loader_cli
  tidy-html5
  timewarrior
  tmate
  tmux
  tmuxinator-completion
  tokei
  tor
  trash
  tree
  '--HEAD universal-ctags/universal-ctags/universal-ctags'
  vim
  watch
  wget
  wp-cli
  youtube-dl
  zsh
  zsh-completions
)

qlexts=(
  betterzipql
  qlcolorcode
  qlimagesize
  qlmarkdown
  qlprettypatch
  qlstephen
  quicklook-csv
  quicklook-json
  suspicious-package
  webpquicklook
)

npm_packages=(
  bower
  commit-msg
  css-loader
  csslint
  ember-cli
  ember-template-lint
  eslint
  extract-loader
  fb-messenger-cli
  file-loader
  fixjson
  generator-assemble
  generator-reveal
  generator-webapp
  grunt-cli
  gulp
  hint
  http-server
  js-yaml
  jshint
  'git+https://github.com/ramitos/jsctags.git'
  lighthouse
  live-server
  livedown
  neovim
  node-sass
  puppeteer
  purify-css
  phantomjs-prebuilt
  sass-lint
  sass-loader
  sloc
  spot
  standard
  stylelint
  stylelint-scss
  stylelint-config-recommended
  stylelint-config-recommended-scss
  stylelint-config-standard
  surge
  swaglint
  tern
  'webpack-dev-server@2'
  'webpack@3'
  write-good
  yarn
  yo
)

pip_packages=(
  bitbucket-cli
  jedi
  python-dateutil
  pylint
  requests
  sass-lint
  terminal_velocity
  vim-vint
  taskwarrior-inthe.am
)

pip3_packages=(
  proselint
  mps-youtube
  neovim
  tasklib
)

user_apps=(
  1password
  bartender
  carbon-copy-cloner
  coconutbattery
  cool-retro-term
  cyberduck
  docker
  firefox
  flash-npapi
  gifrocket
  google-chrome
  google-chrome-canary
  google-backup-and-sync
  iexplorer
  imageoptim
  iterm2
  java
  karabiner-elements
  keyboard-maestro
  keycastr
  mac2imgur
  nosleep
  qutebrowser
  slack
  spectacle
  sublime-text
  teamviewer
  textexpander
  torbrowser
  tunnelbear
  vagrant
  virtualbox
  vlc
)

# Check for Homebrew,
# Install if we don't have it
if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "Setting up homebrew..."
brew doctor
brew update

for tap in "${brew_taps[@]}"; do
    brew tap $tap
done

echo "Installing user brews..."
for formula in "${user_brews[@]}"; do
    brew install $formula
done

# update pip stuff for the newly installed python
echo "Updating pip..."
pip install --upgrade setuptools
pip install --upgrade pip
easy_install iso8601

# install python packages
echo "Installing pip packages..."
pip install "${pip_packages[@]}"
echo "Installing pip3 packages..."
pip3 install "${pip3_packages[@]}"

# install composer packages
composer global require "asm89/twig-lint" "@stable" # dep of SublimeLinter-twig

# install npm packages
echo "Installing npm packages..."
npm install -g "${npm_packages[@]}"

# install the cask
brew tap caskroom/cask

# install user_apps
echo "Installing apps..."
for formula in "${user_apps[@]}"; do
    brew cask install $formula
done

# add `subl` command
ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

# set up Neovim.app
ln -s /usr/local/opt/neovim-dot-app/Neovim.app /Applications

# install vim-anywhere and use Neovim.app instead
curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/install | bash
echo '/usr/local/opt/neovim-dot-app/bin/gnvim' > ~/.vim-anywhere/.path

# install Prey with API key prompt
read -p "Set up Prey https://panel.preyproject.com/settings/user-profile:" prey_api_key

# echo "installing quicklook extensions..."
brew cask install "${qlexts[@]}"

# fetch latest base16
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

# pull in neosnippets fork
git clone https://github.com/sh78/neosnippet-snippets.git ~/neosnippets-snippets
