#!/usr/bin/env bash

user_gems=(
    bropages
    bundler
    colorls
    compass
    foreman
    lolcat
    neovim
    pg
    pry
    rails
    sass
    thin
    tmuxinator
)

# check that rbenv is ok
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash

# get the lastest stable ruby build through rbenv
rubyv=$(rbenv install -l | grep -v - | tail -1 | sed -e 's/^[ \t]*//')
rbenv install $rubyv
rbenv init
rbenv global $rubyv

# install gems
echo "installing gems..."
gem install "${user_gems[@]}" --no-document
