#!/usr/bin/env bash

# Apps that need some manual loving
apps=(
    "1Password"
    "Bartender 3"
    "iTerm2"
    "TextExpander"
)

for app in ${apps[@]}; do
    open "/Applications/$app.app"
done

echo "opening chunkwm tiling window manager and khd..."
brew services start crisidev/chunkwm/chunkwm
brew services start koekeishiya/formulae/khd

echo "Installing bundles in vim..."
vim +PlugInstall
nvim +PlugInstall +UpdateRemotePlugins

echo "Setting up phpcd linting..."
pushd ~/.vim/bundle/phpcd.vim/ && composer update && pushd
pushd ~/.vim/bundle/phpcd.vim/vendor/lvht/msgpack-rpc/ && composer update && pushd
