#!/usr/bin/env bash

echo "setting preferences..."
sleep 1
bash ./prefs

echo "running installers..."
sleep 1
bash ./installers

echo "opening Drive, start sync process now and press [Enter] key when fully syned..."
open /Applications/Google \ Drive.app

echo "setting up fish..."
sleep 1
bash ./fish

echo "setting up ruby, rbenv, and gems..."
sleep 1
bash ./ruby

read -p "restoring from mackup backup (sym links). press [Enter] to continue when Google Drive is fully synced..."
sleep 1
bash ./mackup

echo "opening some apps for manual setup..."
sleep 1
bash ./run_apps
