#!/bin/bash

# calculate battery %
cur_power=`ioreg -w0 -l | grep CurrentCapacity | awk '{print $5}'`
max_power=`ioreg -w0 -l | grep MaxCapacity | awk '{print $5}'`
bat_percent=`echo "scale=2;$cur_power / $max_power" | bc`
bat_percent=`echo "$bat_percent * 100" | bc | sed 's/.00//'`

# battery cycles
# cyc_count=`ioreg -w0 -l | grep "Cycle Count" | awk 'BEGIN { FS = "=" } ; {print $8}' | awk 'BEGIN { FS = "}" } ; {print $1}'`

# time remaining to charge || until depletion
minutesRemaining=$(ioreg -l | grep -i 'TimeRemaining' | sed 's/[^0-9]//g')
fhrs=$(($minutesRemaining / 60))
fmins=$(($minutesRemaining % 60))
if [[ ${#fmins} -eq 1 ]]; then
    fmins="0$fmins"
fi
timeLeft="$fhrs:$fmins"

# show stats
my_ac_adapt=`ioreg -w0 -l | grep ExternalConnected | awk '{print $5}'`

echo "$bat_percent%"
echo "$timeLeft"
# echo "$cyc_count"