#!/bin/sh
# Heuristically extract compressed archives with progress bar and ETA
# TODO: support more than tar

VERBOSE=''
if [ "$1" = "-v" ]; then
    VERBOSE=1
    shift
fi

HASPV=''
if command -v pv >/dev/null ; then
    HASPV=1
else
    echo "Install `pv` for progress bars."
    echo "Continuing without progress bars..."
fi

if [ -z "$1" ]; then
    echo "Usage: extract <file> [file2] [file3]"
echo "Supported extensions:
    zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz|tar.bz2"
    exit 1
fi

for archive in "$@"; do
    if [ -f "$archive" ] ; then
        case "${archive%,}" in
            *.tar)
                if [ $VERBOSE ]; then
                    tar xvf "$archive"
                elif [ $HASPV ]; then
                    pv "$archive" | tar xf - -C .
                else
                    tar xf "$archive"
                fi
            ;;
            *.tar.gz|*.tgz)
                if [ $VERBOSE ]; then
                    tar xzvf "$archive"
                elif [ $HASPV ]; then
                    pv "$archive" | tar xzf - -C .
                else
                    tar xzf "$archive"
                fi
            ;;
            *.tar.bz2|*.tar.bz|*.tar.bz)
                if [ $VERBOSE ]; then
                    tar xjvf "$archive"
                elif [ $HASPV ]; then
                    pv "$archive" | tar xjf - -C .
                else
                    tar xjf "$archive"
                fi
            ;;
            *.tar.xz|*.txz)
                if [ $VERBOSE ]; then
                    tar xJvf "$archive"
                elif [ $HASPV ]; then
                    pv "$archive" | tar xJf - -C .
                else
                    tar xJf "$archive"
                fi
            ;;
            *.lzma)
                unlzma ./"$archive"
            ;;
            *.bz2)
                bunzip2 ./"$archive"
            ;;
            *.rar)
                unrar x -ad ./"$archive"
            ;;
            *.gz)
                gunzip ./"$archive"
            ;;
            *.zip)
                if [ $HASPV ]; then
                    # TODO: pv not accurate
                    unzip ./"$archive" | pv -l >/dev/null
                else
                    unzip ./"$archive"
                fi
            ;;
            *.z)
                uncompress ./"$archive"
            ;;
            *.7z|*.arj|*.cab|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.rpm|*.udf|*.wim|*.xar)
                7z x ./"$archive"
            ;;
            *.xz)
                unxz ./"$archive"
            ;;
            *.exe)
                cabextract ./"$archive"
            ;;
            *)
                echo "extract: '$archive' - unknown archive method"
                return 1
            ;;
        esac
    else
        echo "extract: '$archive' - file does not exist"
        return 1
    fi
done
