#!/bin/bash

sudo -v

sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y

npm update -g

sudo gem update

nvim +PlugUpdate

# Now check for an OS release
sudo apt full-upgrade
sudo pop-upgrade release upgrade
