
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-19T13:50:43-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "115bdc164c40cca4095a0784c8a8f93c2ae8120e",
 "version": "4.1.1a8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
